# Generated by Django 5.0.4 on 2024-04-26 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0011_alter_reservation_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='Booking_status',
            field=models.IntegerField(choices=[(0, 'Waiting for approval'), (1, 'Approved'), (2, 'Denied'), (3, 'Waiting to be collected'), (4, 'Collected'), (5, 'Not returned'), (6, 'Returned')], null=True),
        ),
    ]
